/** Auto-generación de borradores tras scoring (score ≥ 7, plan pago) */

import { createAdminClient } from "@/lib/supabase/admin";
import { isPlanAtLeast } from "@/lib/payments/plans";
import type { Plan, Platform, UserProduct } from "@/types";
import {
  checkDraftLimit,
  generateDraftForSignal,
  generateDraftReply,
} from "@/lib/drafts";
import { DRAFT_MIN_SCORE } from "@/lib/drafts/constants";

export { DRAFT_MIN_SCORE };

type ProductContext = Pick<
  UserProduct,
  "name" | "description" | "target_customer" | "pain_points"
>;

export function shouldAutoGenerateDraft(score: number, plan: Plan): boolean {
  return score >= DRAFT_MIN_SCORE && isPlanAtLeast(plan, "starter");
}

export async function autoGenerateDraftForNewSignal(input: {
  signalId: string;
  userId: string;
  plan: Plan;
  score: number;
  post: {
    title: string | null;
    body: string | null;
    platform: Platform;
    intent_reason: string | null;
  };
  product: ProductContext;
}): Promise<{ generated: boolean; error?: string }> {
  if (!shouldAutoGenerateDraft(input.score, input.plan)) {
    return { generated: false };
  }

  const limit = await checkDraftLimit(input.plan, input.userId);
  if (!limit.allowed) {
    return { generated: false, error: limit.reason };
  }

  try {
    const draft = await generateDraftReply({
      post: {
        title: input.post.title,
        body: input.post.body,
        platform: input.post.platform,
        intent_reason: input.post.intent_reason,
      },
      product: input.product,
    });

    const supabase = createAdminClient();
    const { error } = await supabase
      .from("signals")
      .update({ draft_reply: draft })
      .eq("id", input.signalId)
      .eq("user_id", input.userId);

    if (error) {
      return { generated: false, error: error.message };
    }

    return { generated: true };
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    return { generated: false, error: msg };
  }
}

/** Al upgradear a plan pago: drafts para las últimas 10 señales elegibles sin borrador */
export async function backfillDraftsOnUpgrade(
  userId: string,
  plan: Plan
): Promise<number> {
  if (!isPlanAtLeast(plan, "starter")) {
    return 0;
  }

  const supabase = createAdminClient();

  const { data: signals } = await supabase
    .from("signals")
    .select("id")
    .eq("user_id", userId)
    .gte("intent_score", DRAFT_MIN_SCORE)
    .or("draft_reply.is.null,draft_reply.eq.")
    .order("found_at", { ascending: false })
    .limit(10);

  if (!signals?.length) {
    return 0;
  }

  let generated = 0;

  for (const row of signals) {
    const result = await generateDraftForSignal({
      signalId: row.id,
      userId,
      plan,
    });
    if (result.success) {
      generated++;
    }
  }

  return generated;
}
